/** Matches backend plan_limits::MODULE_CATALOG (25 tenant sidebar modules). */
export const TENANT_MODULE_CATALOG = [
    { key: 'dashboard', label: 'Dashboard' },
    { key: 'users', label: 'Users & Roles' },
    { key: 'centers', label: 'Branches' },
    { key: 'departments', label: 'Departments' },
    { key: 'designations', label: 'Designations' },
    { key: 'careers', label: 'Job Postings' },
    { key: 'job_applications', label: 'Applications' },
    { key: 'chat', label: 'Team Chat' },
    { key: 'attendance', label: 'Attendance' },
    { key: 'shifts', label: 'Shifts' },
    { key: 'biometric', label: 'Biometric Devices' },
    { key: 'manual_attendance', label: 'Manual Attendance' },
    { key: 'leave', label: 'Leave Requests' },
    { key: 'leave_manage', label: 'Manage Leave' },
    { key: 'holidays', label: 'Holidays' },
    { key: 'payroll', label: 'Salaries & Payroll' },
    { key: 'my_payslips', label: 'My Payslips' },
    { key: 'doctor_reports', label: 'Doctor Reports' },
    { key: 'my_doctor_reports', label: 'My Doctor Reports' },
    { key: 'workflows', label: 'Workflows' },
    { key: 'tasks', label: 'Tasks & Activities' },
    { key: 'projects', label: 'Projects' },
    { key: 'reports', label: 'Reports' },
    { key: 'subscription', label: 'Subscription' },
    { key: 'notifications', label: 'Notifications' },
    { key: 'support', label: 'Support' },
    { key: 'settings', label: 'App Settings' },
] as const;
